### ISSUE TITLE
please update remote URL to salsa

### ISSUE THREAD

**Issue by sandrotosi** [p1otr/pypi2deb#18]
https://github.com/p1otr/pypi2deb/blob/7c1a391b211a41294706145168b6b9748911e85c/profiles/dpmt/hooks/post#L18 still points to alioth, can you please update it to point to salsa? thanks!

**Comment by sandrotosi** [comment]
and since you are at it, you can remove the git-dpm integration from the same file - thanks!

**Comment by p1otr** [comment]
fixed in last release (sorry, forgot to mention it in commit's description)
