### ISSUE TITLE
is this project still maintained?

### ISSUE THREAD

**Issue by sandrotosi** [p1otr/pypi2deb#26]
Hey Piotr,
i'm wondering if you're still maintaining this project. there are some outstanding issues and PRs unaddressed by some time; i was planning on submit some changes but i fear that may be a waste of time if not merged/released.

thanks!

**Comment by p1otr** [comment]
I am. I will release new version soon.

**Comment by sandrotosi** [comment]
great to hear! but when is "soon"? do you have a list of changes you plan on making (or maybe even already completed)? dont want to duplicate work

**Comment by leggewie** [comment]
looking forward to a new release

Many thanks to both of you for your work.

**Comment by sandrotosi** [comment]
@leggewie there's been some continued development at https://github.com/sandrotosi/pypi2deb/tree/morph if you want to test things out

**Comment by sandrotosi** [comment]
the project has been moved to https://salsa.debian.org/python-team/tools/pypi2deb and i was made part of the maintainers
